### ISSUE TITLE
Rainloop webmail client is removed after the installation

### ISSUE THREAD

**Issue by merkys7** [litespeedtech/ls-cloud-image#14]
Hello,
In following file: https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/cybersetup.sh

I can see the following sequence: 
Install CyberPanel
Remove RainLoop

Is it correct?

Perhaps it should be:
Remove RainLoop
Install CyberPanel

Because after install, user cannot access RainLoop webclient

**Comment by merkys7** [comment]
Perhaps contributor such as @Code-Egg could answer this question? Perhaps the RainLoop WebClient is not secure?

**Comment by Code-Egg** [comment]
Hi @merkys7 ,

Right, due to a request from the platform provider that we should not include rainloop package from the original installation, so we install it when user launch it.  Feel free to give it a try on existing CyberPanel Image, rainloop should be there. 

Check here https://github.com/litespeedtech/ls-cloud-image/blob/master/Cloud-init/per-instance.sh#L534

**Comment by merkys7** [comment]
Thank you very much!
