### ISSUE TITLE
PhpMyAdmin Permission Errors?

### ISSUE THREAD

**Issue by KevinB97** [litespeedtech/ls-cloud-image#17]
Hi there,

I am receiving the following errors when accessing PhpMyAdmin after installing the OpenLiteSpeed-WordPress image via Linode:

https://paste.pics/8XWOF
https://paste.pics/8XWOP

Any idea how to fix this?

Thanks

**Comment by Code-Egg** [comment]
Hi @KevinB97 ,

Can you tell me this issue happens on which OS? Because I just tried it on Ubuntu 18 but did not see it. 

About `The &cfg['TempDir']..` issue is due to new phpmyadmin missed the tmp folder. Fix method is easy, just create a tmp folder under the phpmyadmin and the warning should just gone.

**Comment by KevinB97** [comment]
I am trying this on CentOS 7, should I be using Ubuntu 18 to prevent any bugs now & in future?

Ok sweet

**Comment by Code-Egg** [comment]
Thanks, I will look into and update here.

**Comment by Code-Egg** [comment]
I can see the issue and found the solution, you can manually fix it by follow command:
```
chown -R nobody:nobody /var/www/phpmyadmin
```
I will fix it on the script at some point.

**Comment by KevinB97** [comment]
Ok thanks I will try it out soon.

Do you recommend running Ubuntu 18 instead of CentOS btw?

**Comment by Code-Egg** [comment]
I recommend both, just choose the one you more comfortable with.

**Comment by Code-Egg** [comment]
Pushed, should works now.
