### ISSUE TITLE
Eric - Ericd ?

### ISSUE THREAD

**Issue by kardos-services** [litespeedtech/ls-cloud-image#43]
Dear Developer's,

I found the following user on the Litespeed server:

`cat /etc/passwd`
eric:x:1001:1002::/home/eric:/bin/bash
globalsupport:x:1002:1003::/home/globalsupport:/bin/bash
ericd:x:1003:1004::/home/ericd:/bin/bash

Are they very important or can they be deleted?

what are they even doing in the system?

Thank you very much!

Regards,

Laszlo

**Comment by Code-Egg** [comment]
Hi @gebaeudemeister 
Thanks for the report, those empty accounts have no access and can be deleted. 
The issue has already been fixed in this [commit](https://github.com/litespeedtech/ls-cloud-image/commit/97091ef0ca29e4af37274ab923216702989fc821#). 
And the new WordPress Image has already been pushed on the marketplace.
